language: ruby
rvm:
  2.3.3

before_install:
  - chmod +x scripts/build.sh


install: gem install jekyll html-proofer jekyll-paginate  
script: scripts/build.sh

branches:
  only:
    - master  # test the master branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    
sudo: false

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

notifications:
  pushover:
    api_key:
      secure: tcWoqC0bj6PgS/J/xHdy5TCOjht/qPl5W2+wbiqedw+mpLL7PulmWbnkr23RdQ0gua6wiXJ29X8pdA+eRF8Ml8pYt1//jY9E86S9BZI2VcpXdukTNBbYQ0CrboGz5hLoa2Ia8yyDYlv4fX/gKhYJtD/bWnJPtyv+fXVIn+Pmaz/hA3OCJgOb/jBQczpdk4G5qSkCQy3B1sDdKQ036+cR/MUfNEY4EioJaGuSVSgn7JuHZDBuZzDtgrzPBALDOZtIjhDygoQFt/iFWPC3RNqkNeasYZU6nDW38k71Hj8n5kRzQz8hT94VF+VpOETGPFc13XWYpso7VLkD7KJqo6V1q8yI7455RLXkos92WMObLvSkj7ERspy0WlqyRyAzbi2kTneoRZjnnMI/js7w6lAifI2/PHyBXHlIPlaBTPhGeBL4urF7LjjguH85e7Wqc2FEtUOrI1HAE5r3gUXk4a0lV1bcKkYBeNlhG9hqBklyn4yvqJ9bVg7nWPZfga8kLx9XTxKGpEfh7DnkF+mftsF1Z7Th8YIXJMXQXEuumkjp66p/hS9lfx+k/GytHWimpCDPbswyBYJwjgcqpuqH6uBozq7s2zrEGNQZjQF7qkLDCVbWXeuHO1NYRSpq3ONkzmh7At80UlDxOmbu9BL/XQFEtFzF/P1o8vSbm6Fk/Y8z864=
    users:
      secure: ORjIC6wFraBUEBdh3RVTWG33u9T4Ebzi8h1Tn+lp6IEteIKHinybxSGnaYHRQIJEMkqFcUl7YcAXcoY2LmADKrDoNIs0BSjoAjjczc/ROYiJFXdtlDpSB4l7SYBD4wc/kpcsdqL/iGKXHXwS6iyAXqmM0zPjEhdaQEGhZdgo5T/mHajVIm8TOymrqhW1CQebRlbyp442+0Dt5pJ5tTdh5Lrc2ef8XyGwpYyMWIbqPQOhx/FRlegV07RETfJ5lNaBLxB/3tdfNt8vXqsE99xThFc01XInBqTIG+j4v2u5h1A9JLuC8bRfSigj1Kf2mD00Gtrk6vu+pKPPV+WmnqzU/Z5vOzWVQDS1ofE06MI1HyGknfuQgxzS3QjUT+LPCrHRB8eqTAo+NFrbRbCB10CFtYJL+l+huFyiO6OGZYgZnrtw2zyJWvwWLsAndWy+vJUAbqORVHrrMVJbZxvUHVdNeeFd7trMLkVBcqcL6B9bgFPV8DqKZYoQZU6pD8KkK9hYIPi8jFRxTcidjJOnTblsv67BCUldRJA6bE4T/WSuZWquu+gd/4DQ/jjQWBPh8Jrt45fT7bU5qeNr+8WEQn/zQiJHpkq7MMNjxmDWZzfo9Wl4Snj65KVRSuPcTiXtNV4m7K3JpY/l+lZyff8iNlJiIGBiz4bCe5biKLl5dEmHz2Y=