language: ruby
rvm:
  2.3.3
  
before_install:
  - chmod +x build.sh
  
install: gem install jekyll html-proofer
script: scripts/build.sh

branches:
  only:
    - master  # test the master branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    
sudo: false

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
