#### Website Information #####

name: Paolo Di Lorenzo
description: This is the personal website and blog of Paolo Di Lorenzo.
author: Paolo Di Lorenzo
author_email: paolo@dilorenzo.pl
author_twitter: dilorenzopl

#### URLs ####

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# List of available categories
category_list:
    - meta
    - ios
    - viz
    - physics

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://dilorenzo.pl

#### Jekyll Options #####

# Markdown engine, `kramdown` is the default processor in Jekyll 3.0.0 and the only one supported by Github Pages.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Paginator
paginate: 4
paginate_path: blog/page:num

# Include the following rubygems
gems: [jekyll-paginate]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, .gitignore, favicon.m]
